### ISSUE TITLE
Add publishing URL to repo setting

### ISSUE THREAD

**Issue by jesseajohnston** [clayzim/test-site-676#1]
Looks great! You can add the publishing URL - https://clayzim.github.io/test-site-676/ - to the repo settings, which makes it quicker to navigate to the live site. If you like.

**Comment by clayzim** [comment]
Thanks for the tip, Jesse! That sounds like a good plan. Is this different than where it says:
> Your site is live at https://clayzim.github.io/test-site-676/

at the page https://github.com/clayzim/test-site-676/settings/pages ?

**Comment by jesseajohnston** [comment]
I think you can check the box there, or you can just cut and paste the URl
into the “about” box

**Comment by clayzim** [comment]
Found the setting you meant. Thanks!
